### ISSUE TITLE
Images not showing

### ISSUE THREAD

**Issue by fabiendostie** [custom-components/sensor.radarr_upcoming_media#15]
No images are showing in poster or fanart layout, they are working for the plex though...

I dont actually get an error, it's just that images are missing, everything else is okay.

HA is whitelisted in my adblocker.

Read both trouble shooting docs did the http://ip+api+start/end date test sucessfully

heres a snippet of the result for api/calendar:
<img width="1094" alt="Screen Shot 2021-02-20 at 6 20 28 AM" src="https://user-images.githubusercontent.com/53846121/108593829-1dcee200-7344-11eb-825d-dbca4aeb68e5.png">

All the info is shown EXCEPT the images.
<img width="852" alt="Screen Shot 2021-02-20 at 6 26 39 AM" src="https://user-images.githubusercontent.com/53846121/108593919-aa79a000-7344-11eb-85e1-c2641e6c0aab.png">

Not using the default Home Assistant Radarr component
Home Assistant 2021.2.3 / Latest Docker Available on a Synology NAS

That's it!

thank you for your time, it's really appreciated!

**Comment by myztillx** [comment]
Do they show in a different browser? Sometimes I am unable to see the images inchrome, but they work on the android mobile app or Firefox.

**Comment by jay-em-Ach** [comment]
@fabiendostie, please see [Troubleshooting](https://github.com/custom-cards/upcoming-media-card/blob/master/troubleshooting.md). The first item says, "Whitelist your HA page in your adblocker..."

After whitelisting your HA server or turning off your adblocker and refreshing the page, the images will appear.

**Comment by maykar** [comment]
Is this still an issue for you?

**Comment by PrzemekSkw** [comment]
Hello, I disable Ublock Origin and see images from Radarr upcoming and Sonarr upcoming but still cannot see upcoming from Emby TV and Movies cards. In Firefox I see info that some images was blocked because it was not sending securely.
Regards.
