### ISSUE TITLE
Radarr became broken, Sonarr is fine.

### ISSUE THREAD

**Issue by starman2k01** [custom-components/sensor.radarr_upcoming_media#23]
Radarr component stopped working with latest HASS upgrade

I have identical Radarr and Sonarr addons (port and API different of course).
Both have worked perfectly until latest HASS update. Now only Sonarr works, Radarr does not.

I followed all troubleshooting guides. I cannot directly access Sonarr via the command line query.
So this *might* be a Sonarr issue, but thought it shared same engine as Radarr which works fine.

No data appears because it gets a 404 error.

**What displays when visiting the API URL from the troubleshooting guide?**
Answered above. 

**Does the default Home Assistant Radarr component work for you?**
Default component does not work either.

**Home Assistant Version**
What version of HA are you running?
2022.2.0

I'm going crazy because it worked fine, broke with zero changes to config file etc. just routine upgrades.

**Comment by iczster** [comment]
Error logs from HA running in docker below. Integration worked for ages (sonarr is fine). Removed and upgraded to the latest version. No Radarr sensor is added or media updated in the card view.

Logger: homeassistant.components.sensor
Source: custom_components/radarr_upcoming_media/sensor.py:113 
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22)) 
First occurred: 16:50:27 (2 occurrences) 
Last logged: 16:50:27

Error adding entities for domain sensor with platform radarr_upcoming_media
Error while setting up radarr_upcoming_media platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 773, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 566, in _async_write_ha_state
    extra_state_attributes = self.extra_state_attributes
  File "/config/custom_components/radarr_upcoming_media/sensor.py", line 113, in extra_state_attributes
    if 'ratings' in movie and movie['ratings']['value'] > 0:
KeyError: 'value'

**Comment by iSteeb** [comment]
Drawing attention to this issue, same logs for me on 2022.2

**Comment by rAdziuB** [comment]
Yep, I also have the same issue on HA 2022.2, but earlier on 2021.12.8 was the same case. So, it is not connected with the newest version of HA.

**Comment by johnalkateb** [comment]
same logs for me started after updating to 2022.2 for myself

> Error logs from HA running in docker below. Integration worked for ages (sonarr is fine). Removed and upgraded to the latest version. No Radarr sensor is added or media updated in the card view.
> 
> Logger: homeassistant.components.sensor Source: custom_components/radarr_upcoming_media/sensor.py:113 Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22)) First occurred: 16:50:27 (2 occurrences) Last logged: 16:50:27
> 
> Error adding entities for domain sensor with platform radarr_upcoming_media Error while setting up radarr_upcoming_media platform for sensor Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities await asyncio.gather(*tasks) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity await entity.add_to_platform_finish() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 773, in add_to_platform_finish self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 566, in _async_write_ha_state extra_state_attributes = self.extra_state_attributes File "/config/custom_components/radarr_upcoming_media/sensor.py", line 113, in extra_state_attributes if 'ratings' in movie and movie['ratings']['value'] > 0: KeyError: 'value'

**Comment by john500y2k** [comment]
same logs for me started after updating to 2022.2 for myself



> Error logs from HA running in docker below. Integration worked for ages (sonarr is fine). Removed and upgraded to the latest version. No Radarr sensor is added or media updated in the card view.
> 
> Logger: homeassistant.components.sensor Source: custom_components/radarr_upcoming_media/sensor.py:113 Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22)) First occurred: 16:50:27 (2 occurrences) Last logged: 16:50:27
> 
> Error adding entities for domain sensor with platform radarr_upcoming_media Error while setting up radarr_upcoming_media platform for sensor Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities await asyncio.gather(*tasks) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity await entity.add_to_platform_finish() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 773, in add_to_platform_finish self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 566, in _async_write_ha_state extra_state_attributes = self.extra_state_attributes File "/config/custom_components/radarr_upcoming_media/sensor.py", line 113, in extra_state_attributes if 'ratings' in movie and movie['ratings']['value'] > 0: KeyError: 'value'

**Comment by decairn** [comment]
The 4.0.4.5922 Radarr version removed the Legacy API.  I wonder if that's the source of issue.

**Comment by Deathbot64** [comment]
having the same issue. Plex and Sonarr are still working fine. Radarr will not load no matter what.

**Comment by ceej23** [comment]
Yep, same as above - recently stopped working.

**Comment by quack3d** [comment]
It's because they added multiple rating sources. Do this and it starts working again: https://github.com/custom-components/sensor.radarr_upcoming_media/pull/21/commits/c6fdb4aeb5c7929ed1b147b2e8163f25a692df25

**Comment by starman2k01** [comment]
sepodele, you are absolutely right. Working.

**Comment by philou669** [comment]
Tanks

**Comment by nebakanezzer** [comment]
> It's because they added multiple rating sources. Do this and it starts working again: [c6fdb4a](https://github.com/custom-components/sensor.radarr_upcoming_media/commit/c6fdb4aeb5c7929ed1b147b2e8163f25a692df25)

I've tried this, both upcoming media and the radarr sensor itself are unavailable. 

edit

it needs to be done to both line 113 and 115. working again.

**Comment by cob94440** [comment]
> > It's because they added multiple rating sources. Do this and it starts working again: [c6fdb4a](https://github.com/custom-components/sensor.radarr_upcoming_media/commit/c6fdb4aeb5c7929ed1b147b2e8163f25a692df25)
> 
> I've tried this, both upcoming media and the radarr sensor itself are unavailable.

Same here

**Comment by phenixtai** [comment]
Ok thanks your the best.
1 - Go to file editor in HA
2 - select the file located here :---> (config) ---->  /custom_components/radarr_upcoming_media/sensor.py
3 - in that file, change the line 113 to 115 .  add ['tmdb'] betwen ['ratings'] and ['value'] : 

################################################################
113                if 'ratings' in movie and movie['ratings']['tmdb']['value'] > 0:
114                    card_item['rating'] = ('\N{BLACK STAR} ' +
115                                           str(movie['ratings']['tmdb']['value']))
################################################################

4 - Save the file and Restart HA
5 - Works

**Comment by ikolsteren** [comment]
The modify as outlined worked for me not it seems - I was just setting it up and didn't have even the sensor
Perfect!

**Comment by fireheadman** [comment]
hopefully this fix can get pushed out soon for HACs to work again?  I'm broken also.

**Comment by CJA85** [comment]
above fix worked perfectly.

**Comment by mkanet** [comment]
This was fixed a while back.  Closing issue.
