### ISSUE TITLE
Repository removed message

### ISSUE THREAD

**Issue by quadcom** [custom-components/sensor.radarr_upcoming_media#39]
I discovered to day that the repository for the Radarr component was removed by HACS

![image](https://github.com/user-attachments/assets/f7f741dd-ae23-4a77-9553-9b14335b2d12)

I went and reinstalled it but again, the error message pops up.

**Comment by quadcom** [comment]
Not sure what happened but third times a charm. I managed to reinstall it and get it working again.

**Comment by mkanet** [comment]
@quadcom Im still waiting for the HACS moderators to add this integration (and all related integrations) permanently to HACS.  After they do that, you wont see that message anymore.
